### ISSUE TITLE
Provide a version of the transformation Dataflow that yields a smaller table.

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/codelabs#52]
The example here https://github.com/googlegenomics/codelabs/tree/master/Java/PlatinumGenomes-variant-transformation works well for hundreds of samples.

It also works fine for thousands of samples, but the table it creates is enormous due to many 0/0 genotypes due to the large number of private and rare variants that reside in larger datasets.

**Comment by pgrosu** [comment]
It might also not be a bad idea to have multiple versions of different datasets that are pre-filtered in different ways as smaller modules - which are used more often - that can also be later joined together as necessary.

**Comment by deflaux** [comment]
fixed!  Leaving it in a branch for now.
* Dataflow pipeline https://github.com/googlegenomics/codelabs/tree/summarizeRefMatches/Java/PlatinumGenomes-variant-transformation
* Updated queries that use the new schema https://github.com/googlegenomics/codelabs/tree/summarizeRefMatches/R/PlatinumGenomes-QC

**Comment by deflaux** [comment]
This is now merged to master and available via ``--summarizeRefMatches=true``.
